# Claudestine Default Workflow
# This workflow is used when no project or global workflow is found.
# Copy and customise this file to:
#   - Project: .claudestine/workflow.yaml
#   - Global:  ~/.config/claudestine/workflow.yaml

name: Implementation Loop
version: 1
description: Default Claudestine workflow for plan implementation

# Variables available in prompts and commands:
#   {plan_path}    - Full path to the plan file
#   {working_dir}  - Working directory for Claude

steps:
  # Step 1: Run /implement_plan until completion or verification needed
  - name: implement
    type: claude
    prompt: |
      /implement_plan @{plan_path} ensure to stop for manual verification items.
    stream: true
    stop_on:
      - "manual verification"
      - "needs human review"
      - "stopping for verification"
      - "please verify"

  # Step 2: Automated verification using available tools
  - name: verify
    type: claude
    prompt: |
      You do the manual testing for me. You may use either:
      - Playwright MCP to test the UI
      - uv run -c to run test commands
      - Spin up services and test endpoints

      Ensure everything is working. Report success/failure with details.
    stream: true
    require_success: true

  # Step 3: Update the plan summary for session continuity
  - name: update_summary
    type: claude
    prompt: |
      Update the summary at the top of the plan ({plan_path}) so the next
      session can understand and continue. Include:
      - Current progress percentage
      - What was completed this session
      - What's next
    stream: true

  # Step 4: Git commit and push (no Claude watermark)
  - name: commit
    type: shell
    commands:
      - git add -A
      - git commit -m "{commit_message}"
      - git push
    skip_if_clean: true

  # Step 5: Clear session for next iteration
  - name: clear
    type: internal
    action: clear_session
