name: Implementation Loop
version: 1
description: Default Claudestine workflow for plan implementation

steps:
  - name: implement
    type: claude
    prompt: |
      Read @{plan_path} and implement ONLY the next incomplete phase (marked as "pending" or "in progress").
      Do not implement multiple phases - stop after completing one phase.
      Ensure to stop for any manual verification items listed in the phase.
      Update the phase status to "complete" when done.
    stream: true

  - name: verify
    type: claude
    prompt: |
      You do the manual testing for me. You may use either:
      - Playwright MCP to test the UI
      - uv run -c to run test commands
      - Spin up services and test endpoints

      Ensure everything is working. Report success/failure with details. Pause after verification.
    stream: true

  - name: update_summary
    type: claude
    prompt: |
      Update the summary at the top of the plan ({plan_path}) so the next
      session can understand and continue. Include:
      - Current progress percentage
      - What was completed this session
      - What's next
    stream: true

  - name: commit
    type: claude
    prompt: |
      Git commit with conventional commits on all the changes, outside of the things that are gitignored of course. Do not leave a claude code watermark. Push the changes.
    stream: true

  - name: clear
    type: internal
    action: clear_session
